config/routes.rb
Restaurant4::Application.routes.draw do
  root :to => 'static_pages#home'

  match '/menu', to: 'static_pages#menu'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def menu
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
  	base_title = "Taqueria Mi Palenque"
  	if page_title.empty?
  	  base_title
  	else
  	  "#{base_title} | #{page_title}"
  	end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Taqueria Mi Palenque", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Menu", menu_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="center hero-unit">
	<div class="delivery">	
		<p>Servicio a Domicilio / Delivery</p>
		<p>Orden minima $20.00</p>
	</div>

	<div class="contact">
		<p>12 W. North Ave.</p>
		<p>Northlake, IL 60164</p>
		<p>Tel: (708)562-6322</p>
	</div>

	<div class="hours">
		<p>Hours</p>
		<p>Mon-Thurs. 9am to 10pm</p>
		<p>Friday 9am to 12am</p>
		<p>Saturday 8am to 12am</p>
		<p>Sunday 8am to 11pm</p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3 sidebar">
          <%= render 'layouts/sidebar' %>
        </div>
        <div class="span9">  
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/_bebidas.html.erb
<div class="text">
	<div class="top-text">
		<p>Horchata / <span class="pink">Rice water </span>Tamarindo / <span class="pink">Tamarind</p></p>
		<p>Melon / <span class="pink">Cantaloupe </span>Jamaica / <span class="pink">Hibiscus flower</span></p>
		<p><span>Medium </span>$1.49</p>
		<p><span>Large </span>$2.49</p>
	</div>

	<table>
		<tr>
			<td>Refresco de lata /<span class="pink">Soda Can</span></td>
			<td class="price">$0.85</td>
		</tr>
		<tr>
			<td>Soda de Botella /<span class="pink">Bottle pop</span></td>
			<td></td>
		</tr>
		<tr>
			<td><span>Sangria, Jarritos, Topochico</span></td>
			<td class="price">$1.49</td>
		</tr>
		<tr>
			<td><span>Coca-Cola or Pepsi</span></td>
			<td class="price">$1.75</td>
		</tr>
		<tr>
			<td>Cafe /<span class="pink">Coffee</span></td>
			<td class="price">$0.99</td>
		</tr>
		<tr>
			<td>Agua /<span class="pink">Bottle Water</span></td>
			<td class="price">$1.00</td>
		</tr>
		<tr>
			<td>Licuados /<span class="pink">Milkshakes</span><span>Large</span></td>
			<td class="price">$3.49</td>
		</tr>
		<tr>
			<td>Fresa<span class="pink">-Strawberry </span>Platano<span class="pink">-banana Chocolate</span><span> Medium</span></td>
			<td class="price">$2.49</td>
		</tr>
	</table>
</div>

app/views/static_pages/_burritos.html.erb
<div class="image">
	<%= image_tag("burrito2.png", alt: "burrito") %>
</div>

<div class="text">
	<p>Carne Asada/<span>Steak </span>Pollo/<span>Chicken </span>Al Pastor/<span>Pork</span></p>
	<h3>$4.99</h3>

	<table>
		<tr>
			<td>Burrito Vegetariano/<span>Veggie Burrito</span></td>
			<td class="price">$4.99</td>
		</tr>
		<tr>
			<td><span>Beans, Cheese, Lettuce, tomato & sour cream</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Burrito Especial con papas y una soda de lata</td>
			<td class="price">$5.99</td>
		</tr>
		<tr>
			<td><span>Burrito with your choice of above meats, fries and can pop</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Burrito Dinner con arroz, frijoles y una soda de lata</td>
			<td class="price">$6.99</td>
		</tr>
		<tr>
			<td><span>Served with your choice of above meats, rice & beans and a can pop</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Chimichanga/<span>Chicken, Steak or pork only</span></td>
			<td class="price">$4.99</td>
		</tr>
		<tr>
			<td><span>Served with lettuce, tomato, cheese, sour cream, guacamole & beans</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Chimichanga Especial <span>con papas y una soda de lata</span></td>
			<td class="price">$5.99</td>
		</tr>
		<tr>
			<td><span>Served with lettuce, tomato, cheese, sour cream, guacamole, fries & can pop</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Chimichanga Dinner <span>con arroz y frijoles y soda de lata</span></td>
			<td class="price">$6.99</td>
		</tr>
		<tr>
			<td></span>Served with lettuce, tomato, cheese, sour cream, guacamole, fries & can pop</span></td>
			<td></td>
		</tr>
	</table>
</div>

app/views/static_pages/_caldos.html.erb
<div class="image">
	<%= image_tag("caldo_res2.png", alt: "caldo de res") %>
</div>

<div class="text">
	<table>
		<tr>
			<td>Caldo de Res <span class="pink">Beef Soup</span></td>
			<td class="price">$5.99</td>
		</tr>
		<tr>
			<td>Caldo de Camaron <span class="pink"> Shrimp Soup</span></td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>Coctel de Camaron <span class="pink"> Shrimp cocktail</span></td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>Caldo de Pollo <span class="pink"> Chicken Soup</span></td>
			<td class="price">$5.99</td>
		</tr>
	</table>
</div>

app/views/static_pages/_cerveza.html.erb
<div class="image">
	<%= image_tag("cubeta2.png", alt: "cubeta de cervezas") %>
</div>

<div class="text">
	<p>importadas y del pais /<span class="pink">Home and imported beer</span></p>
	<p>en botella /<span class="pink">Bottle beer</p>
	<p><ul><li>Modelo Especial</li><li>Negra Modelo</li><li>Sol</li></ul></p>
	<p><ul><li>XX Lager</li><li>Carta Blanca</li><li>Bohemia</li></ul></p>
	<p><ul><li>Pacifico</li><li>Tecate</li><li>Victoria</li><li>Corona</li></ul></p>
	<p>$3.99</p>
	<p><ul><li>Budweiser</li><li>Bud Light</li></ul></p>
	<p>$2.99</p>	
</div>

app/views/static_pages/_desayunos.html.erb
<div class="image">
	<%= image_tag("desayuno_mi_palenque2.png", alt: "desayuno mi palenque") %>
</div>

<div class="text">
	<table>
		<tr>
			<td>Desayuno Mi Palenque</td>
			<td class="price">$9.99</td>
		</tr>
		<tr>
			<td>3 Huevos <span>con jamon o Chorizo a la Mexicana</span></td>
			<td class="price">$5.99</td>
		</tr>
		<tr>
			<td>Chilaquiles Verdes o Rojos</td>
			<td></td>
		</tr>
		<tr>
			<td>con huevo <span>with eggs</span></td>
			<td class="price">$5.99</td>
		</tr>
		<tr>
			<td>con Carne <span>with meath</span></td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>con huevo y carne <span>with meat & eggs</span></td>
			<td class="price">$9.99</td>
		</tr>	
	</table>
</div>

app/views/static_pages/_mariscos.html.erb
<div class="image">
	<%= image_tag("camaron_empanizado2.png", alt: "camaron empanizado") %>
</div>

<div class="text">
	<table>
		<tr>
			<td>Camarones Empanizados <span class="pink">Breaded Shrimp dinner</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Camarones al mojo de ajo <span class="pink">Breaded</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>	
			<td>Camarones a la Diabla <span class="pink">Shrimp in hot tomato sauce</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>	
			<td>Fajitas de Camaron <span class="pink">Shrimp fajitas</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>	
			<td>Huachinango <span class="small">al Mojo de Ajo a la Diabla o a la veracruzana </span></td>
			<td class="price">$14.99</td>
		</tr>
		<tr>
			<td><span class="pink">Red snapper in garlic sauce or Devil's or veracruzana Style</span></td>
			<td></td>
		</tr>	
		<tr>
			<td>Filete de Tilapia Empanizada <span class="pink">Breaded fillet of tilapia</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Filete de Tilapia a la Plancha <span class="pink">Fillet of tilapia</span></td>
			<td class="price">$10.99</td>
		</tr>
	</table>
</div>


app/views/static_pages/_platillos.html.erb
<div class="image">
	<%= image_tag("bistec_mexicana2.png", alt: "bistec a la mexicana") %>
</div>

<div class="text">
	<p>Servidos con arroz, frijoles y ensalada <span class="pink">Served with rice, beans & salad</span></p>

	<table>
		<tr>
			<td>Mi Palenque Especial</td>
			<td class="price">$12.99</td>
		</tr>
		<tr>
			<td>Pollo a la Parrilla <span>Grilled chicken</span></td>
			<td class="price">$12.99</td>
		</tr>
		<tr>
			<td>1/2 Pollo a la Parrilla <span>Half grilled chicken</span></td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>Fajitas de Pollo o Bistec <span>Chicken or Steak</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Bistec a la Mexicana</td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Platillo de Carne Asada <span>Skirt Steak Dinner</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Platillo de Milanesa <span>Breaded steak dinner</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Platillo de Cecina <span>Marinated steak strips</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Chicharron en Salsa Verde<span>Pork skin</span></td>
			<td class="price">$10.99</td>
		<tr>
			<td>Bistec con Rajas y Queso</td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Pechuga de Pollo a la Mexicana</td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td><span>Chicken breast served in tomato sauce with onion and jalapeños</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Pechuga de Pollo en Salsa Verde y Queso</td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Chiles Rellenos <span>2 stuffed Peppers</span></td>
			<td class="price">$8.99</td>
		</tr>
		<tr>
			<td>Guisado de puerco en Salsa Verde</td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>3 Enchiladas en Salsa Verde o Roja</td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>3 Flautas Especial con Arroz y Frijoles</td>
			<td class="price">$6.99</td>
		</tr>
		<tr>
			<td>Bistec en chile de arbol <span>Sliced steak in chile de arbol sauce</span></td>
			<td class="price">$10.99</td>
		</tr>
		<tr>
			<td>Pollo en Mole poblano <span>Chicken in poblano mole sauce</span></td>
			<td class="price">$7.99</td>
		</tr>
		<tr>
			<td>Carne Zamora</td>
			<td class="price">$12.99</td>
		</tr>
	</table>
</div>

app/views/static_pages/_quesadillas.html.erb
<div class="image">
	<%= image_tag("quesadilla2.png", alt: "quesadilla") %>
</div>

<div class="text">
	<table>
		<tr>
			<td>Huitlacoche, Champiñon, Flor de Calabaza
			<span class="pink">corn fungus, Mushrooms, squash blossom</span></td>
			<td class="price">$3.99</td>
		</tr>
		<tr>
			<td>O la carne de su preferencia <span class="pink">your choice of meat</span></td>
			<td class="price">$4.99</td>
		</tr>	
	</table>
</div>

app/views/static_pages/_sandwiches.html.erb
<div class="text">
	<table>
		<tr>
			<td>Hamburguesa con Papas Fritas</td>
			<td class="price">$3.50</td>
		</tr>
		<tr>
			<td><span class="pink">Cheese burger with fries</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Hot Dog</td>
			<td class="price">$1.50</td>
		</tr>
	</table>
</div>

app/views/static_pages/_side-dishes.html.erb
<div class="image">
	<%= image_tag("quesadilla2.png", alt: "quesadilla") %>
</div>

<div class="text">
	<table>
		<tr>
			<td>Frijoles/<span class="pink">Beans</span></td>
			<td class="price">$1.99</td>
		</tr>
		<tr>
			<td>Arroz/<span class="pink">Rice</span></td>
			<td class="price">$1.99</td>
		</tr>
		<tr>
			<td>Cebollitas Asadas/<span class="pink">Grilled onions</span></td>
			<td class="price">$2.49</td>
		</tr>
		<tr>
			<td>Papas Fritas/<span class="pink">Fries</span></td>
			<td class="price">$1.99</td>
		</tr>
		<tr>
			<td>Papas Fritas con Queso/<span class="pink">Fries with Cheese</span></td>
			<td class="price">$2.99</td>
		</tr>
		<tr>
			<td>1 Quesadilla Mediana</td>
			<td class="price">$1.99</td>
		</tr>
		<tr>
			<td>1 Quesadilla Mediana con Carne/<span class="pink">Quesadilla with Meat</span></td>
			<td class="price">$2.99</td>
		</tr>
		<tr>
			<td>1 Quesadilla grande/<span class="pink">Quesadilla</span></td>
			<td class="price">$4.99</td>
		</tr>
		<tr>
			<td>3 Flautas de Pollo/<span class="pink">3 Chicken flautas</span></td>
			<td class="price">$4.99</td>
		</tr>
		<tr>
			<td><span class="pink">Served with lettuce, tomato, cheese, sour cream and guacamole</span></td>
			<td></td>
		</tr>
		<tr>
			<td>6 Chicken Nuggets</td>
			<td class="price">$1.99</td>
		</tr>
		<tr>
			<td>6 Nuggets con Papas fritas</td>
			<td class="price">$3.99</td>
		</tr>
		<tr>
			<td><span class="pink">6 Chicken Nuggets with fries</span></td>
			<td></td>
		</tr>
	</table>
</div>

app/views/static_pages/_tortas.html.erb
<div class="text">
	<p class="pink">Includes: Beans, Cheese, Lettuce, tomato & sour cream</p>

	<table>
		<tr>
			<td>Carne Asada, Pollo, Al Pastor, Jamon, Chorizo, Milanesa</td>
			<td class="price">$4.49</td>
		</tr>
		<tr>
			<td><span>Steak, Chicken, Pork, Ham, Mexican Sausage, Breaded Steak</span></td>
			<td></td>
		</tr>
		<tr>
			<td>Torta de Cecina <span>Marinated steak sandwich</span></td>
			<td class="price">$5.49</td>
		</tr>
		<tr>
			<td>Torta Especial con papas y una soda de lata</td>
			<td class="price">$5.99</td>
		</tr>
		<tr>
			<td>Torta Dinner con arroz, frijoles y una soda de lata</td>
			<td class="price">$6.99</td>
		</tr>
		<tr>
			<td><span>Served with your choice of above meats, rice & beans and a can pop</span></td>
			<td></td>
		</tr>
	</table>
</div>

app/views/static_pages/_tostadas.html.erb
<div class="text">
	<p><span>Con frijoles, queso, lechuga, jitomate y crema</span></p>
	<p><span>Includes: Beans, Cheese, Lettuce, tomato & sour cream</span></p>
	<p class="red">$2.99</p>
	<p>Carne Asada/<span class="pink">Steak </span>Pollo/<span class="pink">Chicken </span>Al Pastor/<span class="pink">Pork</span></p>
	<p>Camaron/<span class="pink">Shrimp </span>Pescado/<span class="pink">Fish</span></p>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Taqueria Mi Palenque</h1>

  <h2>
    Authentic Mexican Food
  </h2>

  <%= link_to "Check out our menu!", menu_path, class: "btn btn-large btn-primary" %>

  <div class="slider-wrapper theme-default">
    <div id="slider" class="nivoSlider">
        <%= image_tag("bistec_chile_arbol2.png", alt: "bistec de chile de arbol", 
			  title: "bistec de chile de arbol") %>
		<%= image_tag("bistec_mexicana2.png",    alt: "bistec a la Mexicana",
              title: "bistec a la Mexicana") %>
    </div>
  </div>

</div>

app/views/static_pages/menu.html.erb
<% provide(:title, 'Menu') %>
<h1 id="title">Our Menu</h1>

<div id="menu-page">
<div id="tabs">
	<ul>
		<li><a href="#tabs-1">Mariscos</a></li>
		<li><a href="#tabs-2">Sopes o Gorditas</a></li>
		<li><a href="#tabs-3">Caldos/Soups</a></li>
		<li><a href="#tabs-4">Side Dishes</a></li>
		<li><a href="#tabs-5">Bebidas/Drinks</a></li>
		<li><a href="#tabs-6">Cerveza/Beer</a></li>
		<li><a href="#tabs-7">Desayunos/Breakfast</a></li>
		<li><a href="#tabs-8">Quesadillas</a></li>
		<li><a href="#tabs-9">Chips & Nachos</a></li>
		<li><a href="#tabs-10">Burritos</a></li>
		<li><a href="#tabs-11">Tortas/Mexican Sandwich</a></li>
		<li><a href="#tabs-12">Platillos/Dinners</a></li>
		<li><a href="#tabs-13">Tacos</a></li>
		<li><a href="#tabs-14">Sandwiches</a></li>
		<li><a href="#tabs-15">Tostadas</a></li>
	</ul>
	<div id="tabs-1">
		<%= render 'mariscos' %>
	</div>
	<div id="tabs-2">
		<%= render 'sopes' %>
	</div>
	<div id="tabs-3">
		<%= render 'caldos' %>
	</div>
	<div id="tabs-4">
		<%= render 'side-dishes' %>
	</div>
	<div id="tabs-5">
		<%= render 'bebidas' %>
	</div>
	<div id="tabs-6">
		<%= render 'cerveza' %>
	</div>
	<div id="tabs-7">
		<%= render 'desayunos' %>
	</div>
	<div id="tabs-8">
		<%= render 'quesadillas' %>
	</div>
	<div id="tabs-9">
		<%= render 'chips' %>
	</div>
	<div id="tabs-10">
		<%= render 'burritos' %>
	</div>
	<div id="tabs-11">
		<%= render 'tortas' %>
	</div>
	<div id="tabs-12">
		<%= render 'platillos' %>
	</div>
	<div id="tabs-13">
		<%= render 'tacos' %>
	</div>
	<div id="tabs-14">
		<%= render 'sandwiches' %>
	</div>
	<div id="tabs-15">
		<%= render 'tostadas' %>
	</div>
</div>

</div><!-- menu-page -->